---
- name: install packages
  pacman:
    # update_cache: yes
    name:
      - alacritty
      - git
      - openssh
      - thunar
      - zsh
      - zsh-completions

      # xorg
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot

      # interface
      - bspwm
      - sxhkd
      - picom
      - dzen2
      - rofi
      - feh
      - gnome-themes-extra
      - adwaita-icon-theme

      # browsers
      - chromium
      - firefox
      - firefox-developer-edition

      # editors
      - neovim
      - vim

      # fonts
      - noto-fonts
      - noto-fonts-emoji
      - ttf-dejavu
      - ttf-roboto
      - ttf-liberation
      - ttf-ubuntu-font-family
      - ttf-freefont
      - ttf-fira-sans
      - ttf-fira-mono
      - ttf-fantasque-sans-mono

      # utils
      - fzf
      - ack
      - fd
      - ripgrep
      - bash-completion
      - sysstat
      - alsa-utils
      - ueberzug
      - translate-shell
      - exa
      - bat

      # network
      - dhcpcd
      - netctl
      - wireless_tools
      - iw
      - wpa_supplicant
      - openvpn

      # audio
      - pulseaudio
      # - pulseaudio-bluetooth
      - mpd
      - libmpdclient
      - ncmpcpp
      - libldac

      # video
      - mpv
      - youtube-dl

      # viewers
      - atril

      # photo
      - gimp
      - scrot
      - gpick

      # dev
      - nodejs
      - npm
      - yarn
      - docker
      - docker-compose
      - gcc
      - clang
      - python-pip
      - base-devel
      - postgresql
      - rustup
      - go
      - go-tools
      # - rust-analyzer

      # other
      - unzip
      - firejail
      - vifm
      - ranger
      - man
      - dialog
      - xclip
      - bluez
      - bluez-utils
      - thunar
      - galculator
      - pacman-contrib
      - sqlite
    state: present

- name: install intel video
  pacman:
    name:
      - xf86-video-intel
    state: present
  when: video == "intel"

- name: install amd video
  pacman:
    name:
      - xf86-video-amdgpu
    state: present
  when: video == "amd"

- name: install acpi
  pacman:
    name:
      - acpi
    state: present
  when: battery == true

- name: install xbacklight
  pacman:
    name:
      - xorg-xbacklight
    state: present
  when: backlight == true

- name: install virtualization tools
  pacman:
    name:
      - qemu
      - libvirt
      - bridge-utils
      - virt-manager
      - virt-viewer
      - spice-vdagent
      - ebtables
      - dnsmasq
    state: present
  when: virt == true

- include: aur.yml
#- include: firejail.yml
